### ISSUE TITLE
Add Gnome 45 Support

### ISSUE THREAD

**Issue by muhammad-ans** [kaanginam/expandable-notifications#14] opened 2023-09-20 13:01 UTC
There are changes in gnome 45 that breaks every extension.
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by galen1423** [comment] 2023-10-05 09:44
+1 for support Gnome 45

Thanks for your work

**Comment by okarika** [comment] 2023-10-24 09:44
+1 for Gnome 45

**Comment by kaanginam** [comment] 2023-10-24 17:26
quickly wokred on a gnome 45 version! As soon as it passes review, would be great if you guys can come back to me and confirm it works fine @galen1423 @okarika @muhammad-ans :D

**Comment by muhammad-ans** [comment] 2023-10-24 17:41
Working as expected. Thanks.

**Comment by Lythenas** [comment] 2023-10-28 10:56
I updated to the latest version on extensions.gnome.org and I'm getting this error on Gnome 45:

```
JS ERROR: Extension expandable-notifications@kaan.g.inam.org: ReferenceError: NotificationSection is not defined
                                           disable@file:///home/ms/.local/share/gnome-shell/extensions/expandable-notifications@kaan.g.inam.org/extension.js:436:9
                                           _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:201:32
                                           _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:619:24
                                           async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:799:20
                                           ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:43:18
                                           _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
                                           _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
                                           _sync@resource:///org/gnome/shell/ui/sessionMode.js:212:14
                                           pushMode@resource:///org/gnome/shell/ui/sessionMode.js:170:14
                                           activate@resource:///org/gnome/shell/ui/screenShield.js:621:34
                                           lock@resource:///org/gnome/shell/ui/screenShield.js:688:14
                                           LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:519:28
                                           _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
                                           _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
                                           @resource:///org/gnome/shell/ui/init.js:21:20

```

I believe I got this error after locking and unlocking.

**Comment by kaanginam** [comment] 2023-10-28 11:24
> I updated to the latest version on extensions.gnome.org and I'm getting this error on Gnome 45:
> 
> ```
> JS ERROR: Extension expandable-notifications@kaan.g.inam.org: ReferenceError: NotificationSection is not defined
>                                            disable@file:///home/ms/.local/share/gnome-shell/extensions/expandable-notifications@kaan.g.inam.org/extension.js:436:9
>                                            _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:201:32
>                                            _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:619:24
>                                            async*_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:799:20
>                                            ExtensionManager/<@resource:///org/gnome/shell/ui/extensionSystem.js:43:18
>                                            _callHandlers@resource:///org/gnome/gjs/modules/core/_signals.js:130:42
>                                            _emit@resource:///org/gnome/gjs/modules/core/_signals.js:119:10
>                                            _sync@resource:///org/gnome/shell/ui/sessionMode.js:212:14
>                                            pushMode@resource:///org/gnome/shell/ui/sessionMode.js:170:14
>                                            activate@resource:///org/gnome/shell/ui/screenShield.js:621:34
>                                            lock@resource:///org/gnome/shell/ui/screenShield.js:688:14
>                                            LockAsync@resource:///org/gnome/shell/ui/shellDBus.js:519:28
>                                            _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
>                                            _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
>                                            @resource:///org/gnome/shell/ui/init.js:21:20
> 
> ```
> 
> I believe I got this error after locking and unlocking.

Thanks for letting me know! I know what the issue is and will fix when I have time.

**Comment by sidevesh** [comment] 2023-11-06 14:09
I see that the new version fixed the error and things are working fine on Gnome 45 now, this can be closed I think.

**Comment by Lythenas** [comment] 2023-11-06 16:20
Ah didn't even see it was updated^^ I can also confirm I don't see the error anymore and it looks like it's working fine.

**Comment by sidevesh** [comment] 2023-11-18 17:26
@muhammad-ans @kaanginam Can you close this now that all issues are resolved and things are working okay

**Closed** 2023-11-18 17:31 UTC
